# Generated by Django 4.1.4 on 2022-12-19 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='languages',
            old_name='desc',
            new_name='ldesc',
        ),
        migrations.RenameField(
            model_name='languages',
            old_name='img',
            new_name='limg',
        ),
        migrations.RenameField(
            model_name='languages',
            old_name='name',
            new_name='lname',
        ),
    ]
