# Generated by Django 4.1.4 on 2022-12-19 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_rename_desc_languages_ldesc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programmers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=250)),
                ('pimg', models.ImageField(upload_to='programmers_pics')),
                ('pdesc', models.TextField()),
            ],
        ),
    ]
